//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KYH_Customer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public int CityID { get; set; }
        public string CityName_CN { get; set; }
        public string CityName_EN { get; set; }
        public string CityName_s { get; set; }
        public string ICode { get; set; }
        public string CountryID { get; set; }
        public string IsCapital { get; set; }
        public string TelCode { get; set; }
        public string ZIPCode { get; set; }
        public Nullable<int> Province { get; set; }
        public Nullable<float> GMTTime { get; set; }
        public string Photo { get; set; }
        public string Photo_s { get; set; }
        public string Introduction { get; set; }
        public Nullable<byte> OrderBy { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateBy { get; set; }
        public string CreateDept { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateBy { get; set; }
        public string UpdateDept { get; set; }
    }
}
