//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KYH_Customer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacts
    {
        public int ContactID { get; set; }
        public string Source { get; set; }
        public int SourceID { get; set; }
        public string City { get; set; }
        public string ContactType { get; set; }
        public string Contact { get; set; }
        public string Remark { get; set; }
        public string Share { get; set; }
        public string CreateBy { get; set; }
        public string CreateDept { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string UpdateBy { get; set; }
        public string UpdateDept { get; set; }
        public System.DateTime UpdateTime { get; set; }
    }
}
