//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KYH_Customer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustBillShip
    {
        public int BillShipID { get; set; }
        public int CustomerID { get; set; }
        public string Inv2EMail { get; set; }
        public string Inv2Comp { get; set; }
        public string Inv2Addr { get; set; }
        public int Inv2City { get; set; }
        public Nullable<int> Inv2State { get; set; }
        public string Inv2Post { get; set; }
        public string Inv2Cnty { get; set; }
        public string Ship2Comp { get; set; }
        public string Ship2Addr { get; set; }
        public int Ship2City { get; set; }
        public Nullable<int> Ship2State { get; set; }
        public string Ship2Post { get; set; }
        public string Ship2Cnty { get; set; }
        public string APName { get; set; }
        public string APTitle { get; set; }
        public string APPhone { get; set; }
        public string APFax { get; set; }
        public string APMobile { get; set; }
        public string APEmail { get; set; }
        public string ARName { get; set; }
        public string ARTitle { get; set; }
        public string ARPhone { get; set; }
        public string ARFax { get; set; }
        public string ARMobile { get; set; }
        public string AREmail { get; set; }
        public string CreateBy { get; set; }
        public string CreateDept { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string UpdateBy { get; set; }
        public string UpdateDept { get; set; }
        public System.DateTime UpdateTime { get; set; }
    
        public virtual CustBillShip CustBillShip1 { get; set; }
        public virtual CustBillShip CustBillShip2 { get; set; }
    }
}
