//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KYH_JigFixture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string EmpID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public string GIPCode { get; set; }
        public string DeptID { get; set; }
        public string ActDeptID { get; set; }
        public string ActPosition { get; set; }
        public string Deputy { get; set; }
        public string JobTitle { get; set; }
        public string Position { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string SurName { get; set; }
        public string GivenName { get; set; }
        public string AliasName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Manager { get; set; }
        public string Substitute { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<System.DateTime> LeftDate { get; set; }
        public string Status { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateBy { get; set; }
        public string CreateDept { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string UpdateBy { get; set; }
        public string UpdateDept { get; set; }
    }
}
