//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KYH_JigFixture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tools_Acquire_Trace
    {
        public int FID { get; set; }
        public System.DateTime ApplyDate { get; set; }
        public string OAFlow_Num { get; set; }
        public string Mat_Code { get; set; }
        public string Mat_Name { get; set; }
        public string Unit { get; set; }
        public decimal Qty { get; set; }
        public Nullable<System.DateTime> Arr_Date { get; set; }
        public string Approval { get; set; }
        public string K3PO_Num { get; set; }
        public Nullable<System.DateTime> K3PO_Date { get; set; }
        public string Supplier { get; set; }
        public Nullable<decimal> K3Qty { get; set; }
        public string Buyer { get; set; }
        public Nullable<System.DateTime> Prop_Arr_Date { get; set; }
        public Nullable<System.DateTime> K3Recv_Date { get; set; }
        public string Remark { get; set; }
        public string K3Unit { get; set; }
        public int UpdateNumber { get; set; }
    }
}
