//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KYH_GetK3POInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadingListAddPOdata_Temp
    {
        public int LPSerial { get; set; }
        public string PONum { get; set; }
        public string Fnumber { get; set; }
        public decimal LoadQty { get; set; }
        public string LoadUnit { get; set; }
        public string Supplier { get; set; }
        public string Material { get; set; }
        public Nullable<decimal> POQty { get; set; }
        public string POUnit { get; set; }
        public string POCurr { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<System.DateTime> NeedDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> USDRate { get; set; }
    }
}
