//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KYH_KnowledgeBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBWords
    {
        public int WordID { get; set; }
        public string WordCode { get; set; }
        public string Name_CN { get; set; }
        public string Name_VN { get; set; }
        public string Name_EN { get; set; }
        public string Del_Flag { get; set; }
        public short OrderBy { get; set; }
        public string Value { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateBy { get; set; }
        public string CreateDept { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string UpdateBy { get; set; }
        public string UpdateDept { get; set; }
    }
}
