//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KYH_Customer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int CompanyID { get; set; }
        public string TableName { get; set; }
        public string FullName_CN { get; set; }
        public string FullName_EN { get; set; }
        public string ShortName { get; set; }
        public string Reg_Addr { get; set; }
        public string Biz_Type { get; set; }
        public Nullable<System.DateTime> Biz_Date { get; set; }
        public string CountryID { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string Location { get; set; }
        public string Postal { get; set; }
        public string Classify { get; set; }
        public string Manager { get; set; }
        public bool Agreement { get; set; }
        public string GoodWill { get; set; }
        public string InBusiness { get; set; }
        public string UrgNotice { get; set; }
        public string Info_CN { get; set; }
        public string Info_EN { get; set; }
        public byte[] Photo { get; set; }
        public byte[] Logo { get; set; }
        public byte[] Banner { get; set; }
        public string Remarks { get; set; }
    }
}
