//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KYH_Customer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public string Icode { get; set; }
        public string CntyName_CN { get; set; }
        public string CntyName_EN { get; set; }
        public string CntyName_s { get; set; }
        public string LongCode { get; set; }
        public string Continent { get; set; }
        public string TelCode { get; set; }
        public Nullable<int> Capital { get; set; }
        public byte[] NationalFlag { get; set; }
        public Nullable<float> GMTTime { get; set; }
        public string GeoSize { get; set; }
        public string Population { get; set; }
        public string Language { get; set; }
        public string Voltage { get; set; }
        public string Currency { get; set; }
        public string Introduction { get; set; }
        public byte[] Photo { get; set; }
        public byte[] Photo_s { get; set; }
        public Nullable<byte> OrderBy { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateBy { get; set; }
        public string CreateDept { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateBy { get; set; }
        public string UpdateDept { get; set; }
    }
}
