//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KYH_ProductPrice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerID { get; set; }
        public string CustType { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public Nullable<int> SysID { get; set; }
        public string K3Code { get; set; }
        public string Class { get; set; }
        public string Belongs { get; set; }
        public string PUR_Name { get; set; }
        public string PUR_Title { get; set; }
        public string PUR_Phone { get; set; }
        public string PUR_Fax { get; set; }
        public string PUR_Mobile { get; set; }
        public string PUR_Email { get; set; }
        public string BankName { get; set; }
        public string BankAddr { get; set; }
        public string iBAN { get; set; }
        public string SWIFT { get; set; }
        public bool IsList { get; set; }
        public string Owner1Name { get; set; }
        public string Owner1Addr { get; set; }
        public string Owner1Web { get; set; }
        public string Owner1Cnty { get; set; }
        public Nullable<System.DateTime> Owner1Date { get; set; }
        public string Owner1Type { get; set; }
        public Nullable<decimal> Owner1Ship { get; set; }
        public string Owner2Name { get; set; }
        public string Owner2Addr { get; set; }
        public string Owner2Web { get; set; }
        public string Owner2Cnty { get; set; }
        public Nullable<System.DateTime> Owner2Date { get; set; }
        public string Owner2Type { get; set; }
        public Nullable<decimal> Owner2Ship { get; set; }
        public string Ref1Name { get; set; }
        public string Ref1Addr { get; set; }
        public string Ref1Contact { get; set; }
        public string Ref1Title { get; set; }
        public string Ref1Phone { get; set; }
        public string Ref2Name { get; set; }
        public string Ref2Addr { get; set; }
        public string Ref2Contact { get; set; }
        public string Ref2Title { get; set; }
        public string Ref2Phone { get; set; }
        public string Curr1 { get; set; }
        public string Curr2 { get; set; }
        public string Curr3 { get; set; }
        public string Curr4 { get; set; }
        public string Yr1Forcast { get; set; }
        public string Yr2Forcast { get; set; }
        public string CreditLimits { get; set; }
        public string CreditTerms { get; set; }
        public Nullable<int> CreditPeriod { get; set; }
        public string CueCode { get; set; }
        public string AnnualRevenue { get; set; }
        public string ServiceBy { get; set; }
        public string CreateBy { get; set; }
        public string CreateDept { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string UpdateBy { get; set; }
        public string UpdateDept { get; set; }
        public System.DateTime UpdateTime { get; set; }
    }
}
