//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KYH_Customer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelectDetail
    {
        public string id { get; set; }
        public int CustomerID { get; set; }
        public int SysID { get; set; }
        public string Class { get; set; }
        public string Belongs { get; set; }
        public string BankName { get; set; }
        public string BankAddr { get; set; }
        public string iBAN { get; set; }
        public string SWIFT { get; set; }
        public bool IsList { get; set; }
        public string Owner1Name { get; set; }
        public string Owner1Addr { get; set; }
        public string Owner1Web { get; set; }
        public string Owner1Cnty { get; set; }
        public Nullable<System.DateTime> Owner1Date { get; set; }
        public string Owner1Type { get; set; }
        public Nullable<decimal> Owner1Ship { get; set; }
        public string Owner2Name { get; set; }
        public string Owner2Addr { get; set; }
        public string Owner2Web { get; set; }
        public string Owner2Cnty { get; set; }
        public Nullable<System.DateTime> Owner2Date { get; set; }
        public string Owner2Type { get; set; }
        public Nullable<decimal> Owner2Ship { get; set; }
        public string Ref1Name { get; set; }
        public string Ref1Addr { get; set; }
        public string Ref1Contact { get; set; }
        public string Ref1Title { get; set; }
        public string Ref1Phone { get; set; }
        public string Ref2Name { get; set; }
        public string Ref2Addr { get; set; }
        public string Ref2Contact { get; set; }
        public string Ref2Title { get; set; }
        public string Ref2Phone { get; set; }
        public string Curr1 { get; set; }
        public string Curr2 { get; set; }
        public string Curr3 { get; set; }
        public string Curr4 { get; set; }
        public string Yr1Forcast { get; set; }
        public string Yr2Forcast { get; set; }
        public string CreditLimits { get; set; }
        public string CreditTerms { get; set; }
        public string PUR_Name { get; set; }
        public string PUR_Title { get; set; }
        public string PUR_Phone { get; set; }
        public string PUR_Fax { get; set; }
        public string PUR_Mobile { get; set; }
        public string PUR_Email { get; set; }
        public string Inv2EMail { get; set; }
        public string Inv2Comp { get; set; }
        public string Inv2Addr { get; set; }
        public int Inv2City { get; set; }
        public int Inv2State { get; set; }
        public string Inv2Post { get; set; }
        public string Inv2Cnty { get; set; }
        public string Ship2Comp { get; set; }
        public string Ship2Addr { get; set; }
        public int Ship2City { get; set; }
        public int Ship2State { get; set; }
        public string Ship2Post { get; set; }
        public string Ship2Cnty { get; set; }
        public string APName { get; set; }
        public string APTitle { get; set; }
        public string APPhone { get; set; }
        public string APFax { get; set; }
        public string APMobile { get; set; }
        public string APEmail { get; set; }
        public string ARName { get; set; }
        public string ARTitle { get; set; }
        public string ARPhone { get; set; }
        public string ARFax { get; set; }
        public string ARMobile { get; set; }
        public string AREmail { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string FullName_CN { get; set; }
        public string FullName_EN { get; set; }
        public string Reg_Addr { get; set; }
        public string ShortName { get; set; }
        public string Classify { get; set; }
        public string Biz_Type { get; set; }
        public Nullable<System.DateTime> Biz_Date { get; set; }
        public int CityID { get; set; }
        public string CountryID { get; set; }
        public string Location { get; set; }
        public string Info_CN { get; set; }
        public string Info_EN { get; set; }
        public string Status { get; set; }
        public string GoodWill { get; set; }
        public string InBusiness { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Web { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateBy { get; set; }
        public string CreateBy1 { get; set; }
        public string CreateDept { get; set; }
        public string CreateDept1 { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string UpdateBy { get; set; }
        public string UpdateDept { get; set; }
        public string XQOwner2Cnty { get; set; }
        public string XQOwner2Type { get; set; }
        public string XQInv2City { get; set; }
        public string XQInv2State { get; set; }
        public string XQInv2Cnty { get; set; }
        public string XQShip2City { get; set; }
        public string XQShip2State { get; set; }
        public string XQShip2Cnty { get; set; }
        public string XQClassify { get; set; }
        public string XQBizType { get; set; }
        public string XQCityID { get; set; }
        public string XQCountryID { get; set; }
        public string XQkhjb { get; set; }
        public string XQKhds { get; set; }
        public string XQOwner1Cnty { get; set; }
        public string XQOwner1Type { get; set; }
        public string XQCurr1 { get; set; }
        public string XQCurr2 { get; set; }
        public string XQCurr3 { get; set; }
        public string XQCurr4 { get; set; }
    }
}
