//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KYH_ProductPrice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetProductPriceList
    {
        public string CreateBy { get; set; }
        public string ShortName { get; set; }
        public string CustomerDisplayName { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Ledger { get; set; }
        public int CPSerial { get; set; }
        public int CustomerID { get; set; }
        public string CustProdCode { get; set; }
        public string CustProdName { get; set; }
        public string PrvCurr { get; set; }
        public decimal PrvUnit { get; set; }
        public string NewPrvUnit { get; set; }
        public string UpdCurr { get; set; }
        public decimal UpdUnit { get; set; }
        public string NewUpdUnit { get; set; }
        public string EffType { get; set; }
        public string EffDetail { get; set; }
        public string Remarks_MD { get; set; }
        public string Remarks_FD { get; set; }
        public string FNumber { get; set; }
        public string Name_EN { get; set; }
        public bool Cancel { get; set; }
        public string CreateDept { get; set; }
        public string UpperDept { get; set; }
        public string DeptID { get; set; }
    }
}
