//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KYH_JigFixture.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class C6Entities2 : DbContext
    {
        public C6Entities2()
            : base("name=C6Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SelectOA_Result> SelectOA(string serial_Num, string k3PO_Num, string buyer, string start_Date, string end_Date, string mat_Code, string mat_Name)
        {
            var serial_NumParameter = serial_Num != null ?
                new ObjectParameter("Serial_Num", serial_Num) :
                new ObjectParameter("Serial_Num", typeof(string));
    
            var k3PO_NumParameter = k3PO_Num != null ?
                new ObjectParameter("K3PO_Num", k3PO_Num) :
                new ObjectParameter("K3PO_Num", typeof(string));
    
            var buyerParameter = buyer != null ?
                new ObjectParameter("Buyer", buyer) :
                new ObjectParameter("Buyer", typeof(string));
    
            var start_DateParameter = start_Date != null ?
                new ObjectParameter("Start_Date", start_Date) :
                new ObjectParameter("Start_Date", typeof(string));
    
            var end_DateParameter = end_Date != null ?
                new ObjectParameter("End_Date", end_Date) :
                new ObjectParameter("End_Date", typeof(string));
    
            var mat_CodeParameter = mat_Code != null ?
                new ObjectParameter("Mat_Code", mat_Code) :
                new ObjectParameter("Mat_Code", typeof(string));
    
            var mat_NameParameter = mat_Name != null ?
                new ObjectParameter("Mat_Name", mat_Name) :
                new ObjectParameter("Mat_Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectOA_Result>("SelectOA", serial_NumParameter, k3PO_NumParameter, buyerParameter, start_DateParameter, end_DateParameter, mat_CodeParameter, mat_NameParameter);
        }
    }
}
