//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KYH_NewEmailDomainPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewEmailDomain2GIP_Select
    {
        public int DNSerial { get; set; }
        public string DomainName { get; set; }
        public System.DateTime FindDate { get; set; }
        public string SourceTypeChinese { get; set; }
        public string SourceType { get; set; }
        public string Remarks { get; set; }
    }
}
