//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CustomerRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomerRes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CustomerRes", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string Bc {
            get {
                return ResourceManager.GetString("Bc", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 办公电话 的本地化字符串。
        /// </summary>
        internal static string Bgdh {
            get {
                return ResourceManager.GetString("Bgdh", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编辑 的本地化字符串。
        /// </summary>
        internal static string Bj {
            get {
                return ResourceManager.GetString("Bj", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 板块 的本地化字符串。
        /// </summary>
        internal static string Bk {
            get {
                return ResourceManager.GetString("Bk", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 为必填项 的本地化字符串。
        /// </summary>
        internal static string Btx {
            get {
                return ResourceManager.GetString("Btx", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 备注 的本地化字符串。
        /// </summary>
        internal static string Bz {
            get {
                return ResourceManager.GetString("Bz", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 采购主管联系 的本地化字符串。
        /// </summary>
        internal static string Cgzglx {
            get {
                return ResourceManager.GetString("Cgzglx", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 创建信息 的本地化字符串。
        /// </summary>
        internal static string Cjxx {
            get {
                return ResourceManager.GetString("Cjxx", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 查看次数/最后更新日期 的本地化字符串。
        /// </summary>
        internal static string Ckcs_zhgxsj {
            get {
                return ResourceManager.GetString("Ckcs/zhgxsj", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 处理 的本地化字符串。
        /// </summary>
        internal static string Cl {
            get {
                return ResourceManager.GetString("Cl", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 成立日期 的本地化字符串。
        /// </summary>
        internal static string Clrq {
            get {
                return ResourceManager.GetString("Clrq", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 次年销售额 的本地化字符串。
        /// </summary>
        internal static string Cnxse {
            get {
                return ResourceManager.GetString("Cnxse", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 次年销售额 的本地化字符串。
        /// </summary>
        internal static string Cnxse1 {
            get {
                return ResourceManager.GetString("Cnxse1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 城市 的本地化字符串。
        /// </summary>
        internal static string Cs {
            get {
                return ResourceManager.GetString("Cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 财务部补充信息 的本地化字符串。
        /// </summary>
        internal static string Cwbbcxx {
            get {
                return ResourceManager.GetString("Cwbbcxx", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 财务部意见 的本地化字符串。
        /// </summary>
        internal static string Cwbyj {
            get {
                return ResourceManager.GetString("Cwbyj", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 成员关系 的本地化字符串。
        /// </summary>
        internal static string Cygx {
            get {
                return ResourceManager.GetString("Cygx", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 传真 的本地化字符串。
        /// </summary>
        internal static string Cz {
            get {
                return ResourceManager.GetString("Cz", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 答 的本地化字符串。
        /// </summary>
        internal static string Da {
            get {
                return ResourceManager.GetString("Da", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 单个文件 的本地化字符串。
        /// </summary>
        internal static string Dangwj {
            get {
                return ResourceManager.GetString("Dangwj", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 打印 的本地化字符串。
        /// </summary>
        internal static string Dayin {
            get {
                return ResourceManager.GetString("Dayin", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 担保函（如有） 的本地化字符串。
        /// </summary>
        internal static string DbhRy {
            get {
                return ResourceManager.GetString("DbhRy", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 导出 的本地化字符串。
        /// </summary>
        internal static string Dc {
            get {
                return ResourceManager.GetString("Dc", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 第二位贸易伙伴信息 的本地化字符串。
        /// </summary>
        internal static string Dewmyhb {
            get {
                return ResourceManager.GetString("Dewmyhb", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 第二位拥有者信息 的本地化字符串。
        /// </summary>
        internal static string Dewyyzxx {
            get {
                return ResourceManager.GetString("Dewyyzxx", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 多个关键字用分号隔开 的本地化字符串。
        /// </summary>
        internal static string Dggjzyfhgk {
            get {
                return ResourceManager.GetString("Dggjzyfhgk", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 东莞毓华电子科技有限公司 的本地化字符串。
        /// </summary>
        internal static string Dghydzkjyxgs {
            get {
                return ResourceManager.GetString("Dghydzkjyxgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 地理位置 的本地化字符串。
        /// </summary>
        internal static string Dlwz {
            get {
                return ResourceManager.GetString("Dlwz", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 答图 的本地化字符串。
        /// </summary>
        internal static string Dt {
            get {
                return ResourceManager.GetString("Dt", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 多个文件 的本地化字符串。
        /// </summary>
        internal static string Duogwj {
            get {
                return ResourceManager.GetString("Duogwj", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 电邮 的本地化字符串。
        /// </summary>
        internal static string Dy {
            get {
                return ResourceManager.GetString("Dy", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 打印人 的本地化字符串。
        /// </summary>
        internal static string dyr {
            get {
                return ResourceManager.GetString("dyr", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 打印时间 的本地化字符串。
        /// </summary>
        internal static string dysj {
            get {
                return ResourceManager.GetString("dysj", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 第一位贸易伙伴信息 的本地化字符串。
        /// </summary>
        internal static string Dywmyhb {
            get {
                return ResourceManager.GetString("Dywmyhb", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 第一位拥有者信息 的本地化字符串。
        /// </summary>
        internal static string Dywyyzxx {
            get {
                return ResourceManager.GetString("Dywyyzxx", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 打印预览 的本地化字符串。
        /// </summary>
        internal static string Dyyl {
            get {
                return ResourceManager.GetString("Dyyl", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 地址 的本地化字符串。
        /// </summary>
        internal static string Dz {
            get {
                return ResourceManager.GetString("Dz", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 第 的本地化字符串。
        /// </summary>
        internal static string D_d {
            get {
                return ResourceManager.GetString("D_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 法定公司名称 的本地化字符串。
        /// </summary>
        internal static string Fdgsmc {
            get {
                return ResourceManager.GetString("Fdgsmc", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 付款条款 的本地化字符串。
        /// </summary>
        internal static string Fktk {
            get {
                return ResourceManager.GetString("Fktk", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 ‎复制 的本地化字符串。
        /// </summary>
        internal static string Fuzhi {
            get {
                return ResourceManager.GetString("Fuzhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 负责人 的本地化字符串。
        /// </summary>
        internal static string Fzr {
            get {
                return ResourceManager.GetString("Fzr", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string Gb {
            get {
                return ResourceManager.GetString("Gb", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 更换图片 的本地化字符串。
        /// </summary>
        internal static string Ghtp {
            get {
                return ResourceManager.GetString("Ghtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 国家 的本地化字符串。
        /// </summary>
        internal static string Gj {
            get {
                return ResourceManager.GetString("Gj", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 关键字 的本地化字符串。
        /// </summary>
        internal static string Gjz {
            get {
                return ResourceManager.GetString("Gjz", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 国际账户号码 (IBAN) 的本地化字符串。
        /// </summary>
        internal static string Gjzhhm {
            get {
                return ResourceManager.GetString("Gjzhhm", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 管理工具 的本地化字符串。
        /// </summary>
        internal static string Glgj {
            get {
                return ResourceManager.GetString("Glgj", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 功能管理 的本地化字符串。
        /// </summary>
        internal static string Gngl {
            get {
                return ResourceManager.GetString("Gngl", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 公司地址 的本地化字符串。
        /// </summary>
        internal static string Gsdz {
            get {
                return ResourceManager.GetString("Gsdz", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 公司介绍（英） 的本地化字符串。
        /// </summary>
        internal static string Gsjsy {
            get {
                return ResourceManager.GetString("Gsjsy", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 公司介绍（中） 的本地化字符串。
        /// </summary>
        internal static string Gsjsz {
            get {
                return ResourceManager.GetString("Gsjsz", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 公司类型 的本地化字符串。
        /// </summary>
        internal static string Gslx {
            get {
                return ResourceManager.GetString("Gslx", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 公司名称 的本地化字符串。
        /// </summary>
        internal static string Gsmc {
            get {
                return ResourceManager.GetString("Gsmc", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 勾上如果是与账单信息相同 的本地化字符串。
        /// </summary>
        internal static string Gsrgsyzdxxxt {
            get {
                return ResourceManager.GetString("Gsrgsyzdxxxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 共 的本地化字符串。
        /// </summary>
        internal static string G_g {
            get {
                return ResourceManager.GetString("G_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 货币 的本地化字符串。
        /// </summary>
        internal static string Hb {
            get {
                return ResourceManager.GetString("Hb", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 还原 的本地化字符串。
        /// </summary>
        internal static string HuanY {
            get {
                return ResourceManager.GetString("HuanY", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 行业 的本地化字符串。
        /// </summary>
        internal static string Hy {
            get {
                return ResourceManager.GetString("Hy", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 行业分类 的本地化字符串。
        /// </summary>
        internal static string Hyfl {
            get {
                return ResourceManager.GetString("Hyfl", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Hossack (越南) 有限公司 的本地化字符串。
        /// </summary>
        internal static string Hynyxgs {
            get {
                return ResourceManager.GetString("Hynyxgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 合作关系 的本地化字符串。
        /// </summary>
        internal static string Hzgx {
            get {
                return ResourceManager.GetString("Hzgx", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 简称 的本地化字符串。
        /// </summary>
        internal static string Jc {
            get {
                return ResourceManager.GetString("Jc", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 基础信息 的本地化字符串。
        /// </summary>
        internal static string Jcxx {
            get {
                return ResourceManager.GetString("Jcxx", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 紧急通告 的本地化字符串。
        /// </summary>
        internal static string Jjtg {
            get {
                return ResourceManager.GetString("Jjtg", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 接收账单的电邮地址 的本地化字符串。
        /// </summary>
        internal static string Jszdddydz {
            get {
                return ResourceManager.GetString("Jszdddydz", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 将文件拖放到此处 的本地化字符串。
        /// </summary>
        internal static string jwjtfdcc {
            get {
                return ResourceManager.GetString("jwjtfdcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 交易货币 的本地化字符串。
        /// </summary>
        internal static string Jyhb {
            get {
                return ResourceManager.GetString("Jyhb", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 建议以电邮为接收账单方式，请提供你的电子邮箱地址 的本地化字符串。
        /// </summary>
        internal static string JyydywjszdfsQtgnddzyxdz {
            get {
                return ResourceManager.GetString("JyydywjszdfsQtgnddzyxdz", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 K3代码 的本地化字符串。
        /// </summary>
        internal static string k3dm {
            get {
                return ResourceManager.GetString("k3dm", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 客户 的本地化字符串。
        /// </summary>
        internal static string Kh {
            get {
                return ResourceManager.GetString("Kh", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 客户代码 的本地化字符串。
        /// </summary>
        internal static string Khdm {
            get {
                return ResourceManager.GetString("Khdm", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 客户递属 的本地化字符串。
        /// </summary>
        internal static string Khds {
            get {
                return ResourceManager.GetString("Khds", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 客户级别 的本地化字符串。
        /// </summary>
        internal static string Khjb {
            get {
                return ResourceManager.GetString("Khjb", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 客户简称 的本地化字符串。
        /// </summary>
        internal static string Khjc {
            get {
                return ResourceManager.GetString("Khjc", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 客户类别 的本地化字符串。
        /// </summary>
        internal static string Khlb {
            get {
                return ResourceManager.GetString("Khlb", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 客户名称 的本地化字符串。
        /// </summary>
        internal static string khmc {
            get {
                return ResourceManager.GetString("khmc", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 客户全称（中） 的本地化字符串。
        /// </summary>
        internal static string Khqc_cn {
            get {
                return ResourceManager.GetString("Khqc_cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 客户全称（英） 的本地化字符串。
        /// </summary>
        internal static string Khqc_en {
            get {
                return ResourceManager.GetString("Khqc_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 客户是否为上市公司 的本地化字符串。
        /// </summary>
        internal static string Khsfwssgs {
            get {
                return ResourceManager.GetString("Khsfwssgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 客户维护列表 的本地化字符串。
        /// </summary>
        internal static string Khwhlb {
            get {
                return ResourceManager.GetString("Khwhlb", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 客户序号 的本地化字符串。
        /// </summary>
        internal static string Khxh {
            get {
                return ResourceManager.GetString("Khxh", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 客户信用详细页 的本地化字符串。
        /// </summary>
        internal static string Khxyxxy {
            get {
                return ResourceManager.GetString("Khxyxxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 客户性质 的本地化字符串。
        /// </summary>
        internal static string Khxz {
            get {
                return ResourceManager.GetString("Khxz", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 联系方式 的本地化字符串。
        /// </summary>
        internal static string Lxfs {
            get {
                return ResourceManager.GetString("Lxfs", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 联系类型 的本地化字符串。
        /// </summary>
        internal static string Lxlx {
            get {
                return ResourceManager.GetString("Lxlx", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 联系人 的本地化字符串。
        /// </summary>
        internal static string Lxr {
            get {
                return ResourceManager.GetString("Lxr", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 联系信息 的本地化字符串。
        /// </summary>
        internal static string Lxxx {
            get {
                return ResourceManager.GetString("Lxxx", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 描述 的本地化字符串。
        /// </summary>
        internal static string Ms {
            get {
                return ResourceManager.GetString("Ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 末页 的本地化字符串。
        /// </summary>
        internal static string My {
            get {
                return ResourceManager.GetString("My", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 每页显示 的本地化字符串。
        /// </summary>
        internal static string Myxs {
            get {
                return ResourceManager.GetString("Myxs", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 年度收入 的本地化字符串。
        /// </summary>
        internal static string Ndsr {
            get {
                return ResourceManager.GetString("Ndsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 全部 的本地化字符串。
        /// </summary>
        internal static string Qb {
            get {
                return ResourceManager.GetString("Qb", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请勾上如果客户为上市实体，不需要提供拥有者信息 的本地化字符串。
        /// </summary>
        internal static string QgsrgkhwssstBxytgyyzxx {
            get {
                return ResourceManager.GetString("QgsrgkhwssstBxytgyyzxx", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请勾上如果选择以邮寄为接收账单方式 的本地化字符串。
        /// </summary>
        internal static string Qgsrgxzyyjwjszdfs {
            get {
                return ResourceManager.GetString("Qgsrgxzyyjwjszdfs", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 确切名称 的本地化字符串。
        /// </summary>
        internal static string Qqmc {
            get {
                return ResourceManager.GetString("Qqmc", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 其他 的本地化字符串。
        /// </summary>
        internal static string Qt {
            get {
                return ResourceManager.GetString("Qt", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 备注：请提供不多于两个主要拥有者信息 的本地化字符串。
        /// </summary>
        internal static string Qtgbdylgzyyyzxx {
            get {
                return ResourceManager.GetString("Qtgbdylgzyyyzxx", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 备注：请提供两家财务水平与我方预期相若的供应商作为贸易参考 的本地化字符串。
        /// </summary>
        internal static string Qtgljcwspywfyqxrdgyszwmyck {
            get {
                return ResourceManager.GetString("Qtgljcwspywfyqxrdgyszwmyck", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string Qx {
            get {
                return ResourceManager.GetString("Qx", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 企业拥有权份% 的本地化字符串。
        /// </summary>
        internal static string Qyyyqf {
            get {
                return ResourceManager.GetString("Qyyyqf", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 群智电子科技 (东莞) 有限公司 的本地化字符串。
        /// </summary>
        internal static string Qzdzkjdgyxgs {
            get {
                return ResourceManager.GetString("Qzdzkjdgyxgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 群智能源科技越南有限公司 的本地化字符串。
        /// </summary>
        internal static string Qznykjynyxgs {
            get {
                return ResourceManager.GetString("Qznykjynyxgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 群智能源科技有限公司 的本地化字符串。
        /// </summary>
        internal static string Qznykjyxgs {
            get {
                return ResourceManager.GetString("Qznykjyxgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 如是现有客户之合约制造商或承包制造商，请列出其成员关系 的本地化字符串。
        /// </summary>
        internal static string RsxykhzhyzzshcbzzsQlcqcygx {
            get {
                return ResourceManager.GetString("RsxykhzhyzzshcbzzsQlcqcygx", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 上传 的本地化字符串。
        /// </summary>
        internal static string Sc {
            get {
                return ResourceManager.GetString("Sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 市场部补充信息 的本地化字符串。
        /// </summary>
        internal static string Scbbcxx {
            get {
                return ResourceManager.GetString("Scbbcxx", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 删除文件 的本地化字符串。
        /// </summary>
        internal static string Schuwj {
            get {
                return ResourceManager.GetString("Schuwj", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 市场商誉 的本地化字符串。
        /// </summary>
        internal static string Scsy {
            get {
                return ResourceManager.GetString("Scsy", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 上传图片 的本地化字符串。
        /// </summary>
        internal static string Sctp {
            get {
                return ResourceManager.GetString("Sctp", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 上传文件 的本地化字符串。
        /// </summary>
        internal static string Scwj {
            get {
                return ResourceManager.GetString("Scwj", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 删除选中文件 的本地化字符串。
        /// </summary>
        internal static string Scxdwj {
            get {
                return ResourceManager.GetString("Scxdwj", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 市场销售部意见 的本地化字符串。
        /// </summary>
        internal static string Scxsbyj {
            get {
                return ResourceManager.GetString("Scxsbyj", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是否共享 的本地化字符串。
        /// </summary>
        internal static string Sfgx {
            get {
                return ResourceManager.GetString("Sfgx", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 上传选中文件 的本地化字符串。
        /// </summary>
        internal static string Shangcxdwj {
            get {
                return ResourceManager.GetString("Shangcxdwj", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 时间 的本地化字符串。
        /// </summary>
        internal static string SHIjian {
            get {
                return ResourceManager.GetString("SHIjian", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 手机 的本地化字符串。
        /// </summary>
        internal static string Sj {
            get {
                return ResourceManager.GetString("Sj", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 首年销售额 的本地化字符串。
        /// </summary>
        internal static string Snxse {
            get {
                return ResourceManager.GetString("Snxse", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 搜索 的本地化字符串。
        /// </summary>
        internal static string Ss {
            get {
                return ResourceManager.GetString("Ss", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 所属板块 的本地化字符串。
        /// </summary>
        internal static string Ssbk {
            get {
                return ResourceManager.GetString("Ssbk", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 所属城市 的本地化字符串。
        /// </summary>
        internal static string Sscs {
            get {
                return ResourceManager.GetString("Sscs", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 所属国家 的本地化字符串。
        /// </summary>
        internal static string Ssgj {
            get {
                return ResourceManager.GetString("Ssgj", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 三位提示码 的本地化字符串。
        /// </summary>
        internal static string Swtsm {
            get {
                return ResourceManager.GetString("Swtsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 首页 的本地化字符串。
        /// </summary>
        internal static string Sy {
            get {
                return ResourceManager.GetString("Sy", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 上一财政年度后的最新管理账目 的本地化字符串。
        /// </summary>
        internal static string Syczndhdzxglzm {
            get {
                return ResourceManager.GetString("Syczndhdzxglzm", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 商业登记证 的本地化字符串。
        /// </summary>
        internal static string Sydjz {
            get {
                return ResourceManager.GetString("Sydjz", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 商业信用申请 的本地化字符串。
        /// </summary>
        internal static string Syxysq {
            get {
                return ResourceManager.GetString("Syxysq", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 上页 的本地化字符串。
        /// </summary>
        internal static string Syy {
            get {
                return ResourceManager.GetString("Syy", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 所在城市 的本地化字符串。
        /// </summary>
        internal static string Szcs {
            get {
                return ResourceManager.GetString("Szcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 三字代码 的本地化字符串。
        /// </summary>
        internal static string Szdm {
            get {
                return ResourceManager.GetString("Szdm", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 提出者 的本地化字符串。
        /// </summary>
        internal static string Tcz {
            get {
                return ResourceManager.GetString("Tcz", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 通过 的本地化字符串。
        /// </summary>
        internal static string Tg {
            get {
                return ResourceManager.GetString("Tg", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 退回 的本地化字符串。
        /// </summary>
        internal static string Th {
            get {
                return ResourceManager.GetString("Th", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 提交审批 的本地化字符串。
        /// </summary>
        internal static string Tjsp {
            get {
                return ResourceManager.GetString("Tjsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 跳转 的本地化字符串。
        /// </summary>
        internal static string Tz {
            get {
                return ResourceManager.GetString("Tz", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 跳至 的本地化字符串。
        /// </summary>
        internal static string Tzhi {
            get {
                return ResourceManager.GetString("Tzhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 条 的本地化字符串。
        /// </summary>
        internal static string T_t {
            get {
                return ResourceManager.GetString("T_t", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 问 的本地化字符串。
        /// </summary>
        internal static string Wen {
            get {
                return ResourceManager.GetString("Wen", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 文件核对清单 的本地化字符串。
        /// </summary>
        internal static string Wjhdqd {
            get {
                return ResourceManager.GetString("Wjhdqd", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 网络 的本地化字符串。
        /// </summary>
        internal static string Wl {
            get {
                return ResourceManager.GetString("Wl", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 问图 的本地化字符串。
        /// </summary>
        internal static string Wt {
            get {
                return ResourceManager.GetString("Wt", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改 的本地化字符串。
        /// </summary>
        internal static string Xg {
            get {
                return ResourceManager.GetString("Xg", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修 改 客 户 联 系 信 息 的本地化字符串。
        /// </summary>
        internal static string Xgkhlxxx {
            get {
                return ResourceManager.GetString("Xgkhlxxx", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修 改  客  户  信  息 的本地化字符串。
        /// </summary>
        internal static string Xgkhxx {
            get {
                return ResourceManager.GetString("Xgkhxx", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修 改 系 统 技 术 知 识 记 录 的本地化字符串。
        /// </summary>
        internal static string Xgxtjszsjl {
            get {
                return ResourceManager.GetString("Xgxtjszsjl", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 序号 的本地化字符串。
        /// </summary>
        internal static string Xh {
            get {
                return ResourceManager.GetString("Xh", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新 建 客 户 联 系 信 息 的本地化字符串。
        /// </summary>
        internal static string Xjkhlxxx {
            get {
                return ResourceManager.GetString("Xjkhlxxx", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新客户信用申请表 的本地化字符串。
        /// </summary>
        internal static string Xkhxysqb {
            get {
                return ResourceManager.GetString("Xkhxysqb", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 姓名 的本地化字符串。
        /// </summary>
        internal static string Xm {
            get {
                return ResourceManager.GetString("Xm", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 取消上传 的本地化字符串。
        /// </summary>
        internal static string Xqsc {
            get {
                return ResourceManager.GetString("Xqsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 销售订单接收实体 的本地化字符串。
        /// </summary>
        internal static string Xsddjsst {
            get {
                return ResourceManager.GetString("Xsddjsst", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 系 统 技 术 知 识 记 录 详 细 的本地化字符串。
        /// </summary>
        internal static string Xtjszsjlxx {
            get {
                return ResourceManager.GetString("Xtjszsjlxx", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 系 统 技 术 知 识 库 的本地化字符串。
        /// </summary>
        internal static string Xtjszsk {
            get {
                return ResourceManager.GetString("Xtjszsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 详细内容 的本地化字符串。
        /// </summary>
        internal static string Xxnr {
            get {
                return ResourceManager.GetString("Xxnr", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 下页 的本地化字符串。
        /// </summary>
        internal static string Xy {
            get {
                return ResourceManager.GetString("Xy", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 信用报告（如 邓白氏商业资料公司） 的本地化字符串。
        /// </summary>
        internal static string XybgRdbssyzlgs {
            get {
                return ResourceManager.GetString("XybgRdbssyzlgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 信用等级 的本地化字符串。
        /// </summary>
        internal static string Xydj {
            get {
                return ResourceManager.GetString("Xydj", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 信用额 的本地化字符串。
        /// </summary>
        internal static string Xye {
            get {
                return ResourceManager.GetString("Xye", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 协议合约 的本地化字符串。
        /// </summary>
        internal static string Xyhy {
            get {
                return ResourceManager.GetString("Xyhy", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 信用期限 的本地化字符串。
        /// </summary>
        internal static string Xyqx {
            get {
                return ResourceManager.GetString("Xyqx", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 信用信息 的本地化字符串。
        /// </summary>
        internal static string Xyxx {
            get {
                return ResourceManager.GetString("Xyxx", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新增 的本地化字符串。
        /// </summary>
        internal static string Xz {
            get {
                return ResourceManager.GetString("Xz", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 下载图片 的本地化字符串。
        /// </summary>
        internal static string Xztp {
            get {
                return ResourceManager.GetString("Xztp", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新 增 系 统 技 术 知 识 记 录 的本地化字符串。
        /// </summary>
        internal static string Xzxtjszsjl {
            get {
                return ResourceManager.GetString("Xzxtjszsjl", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 邮编 的本地化字符串。
        /// </summary>
        internal static string Yb {
            get {
                return ResourceManager.GetString("Yb", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 预测销售量 的本地化字符串。
        /// </summary>
        internal static string Ycxsl {
            get {
                return ResourceManager.GetString("Ycxsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 页 的本地化字符串。
        /// </summary>
        internal static string Ye {
            get {
                return ResourceManager.GetString("Ye", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 应付账款联系信息 的本地化字符串。
        /// </summary>
        internal static string Yfzklxxx {
            get {
                return ResourceManager.GetString("Yfzklxxx", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 银行国际代码 (SWIFT) 的本地化字符串。
        /// </summary>
        internal static string Yhgjdm {
            get {
                return ResourceManager.GetString("Yhgjdm", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 银行资信证明（如有） 的本地化字符串。
        /// </summary>
        internal static string YhzxzmRy {
            get {
                return ResourceManager.GetString("YhzxzmRy", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 越南文 的本地化字符串。
        /// </summary>
        internal static string Ynw {
            get {
                return ResourceManager.GetString("Ynw", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 预期信用条款 的本地化字符串。
        /// </summary>
        internal static string Yqxytk {
            get {
                return ResourceManager.GetString("Yqxytk", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 应收账款联系信息 的本地化字符串。
        /// </summary>
        internal static string Yszklxxx {
            get {
                return ResourceManager.GetString("Yszklxxx", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 英文 的本地化字符串。
        /// </summary>
        internal static string Yw {
            get {
                return ResourceManager.GetString("Yw", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 英文名称 的本地化字符串。
        /// </summary>
        internal static string Ywmc {
            get {
                return ResourceManager.GetString("Ywmc", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 营业地址 的本地化字符串。
        /// </summary>
        internal static string Yydz {
            get {
                return ResourceManager.GetString("Yydz", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 拥有者名称 的本地化字符串。
        /// </summary>
        internal static string Yyzmc {
            get {
                return ResourceManager.GetString("Yyzmc", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 （英-） 的本地化字符串。
        /// </summary>
        internal static string Y_Y {
            get {
                return ResourceManager.GetString("Y_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 职称 的本地化字符串。
        /// </summary>
        internal static string Zc {
            get {
                return ResourceManager.GetString("Zc", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 注册地址 的本地化字符串。
        /// </summary>
        internal static string Zcdz {
            get {
                return ResourceManager.GetString("Zcdz", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 注册国家 的本地化字符串。
        /// </summary>
        internal static string Zcgj {
            get {
                return ResourceManager.GetString("Zcgj", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 注册类型 的本地化字符串。
        /// </summary>
        internal static string Zclx {
            get {
                return ResourceManager.GetString("Zclx", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 注册日期 的本地化字符串。
        /// </summary>
        internal static string Zcrq {
            get {
                return ResourceManager.GetString("Zcrq", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 账单信息 的本地化字符串。
        /// </summary>
        internal static string Zdxx {
            get {
                return ResourceManager.GetString("Zdxx", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 账单信息 的本地化字符串。
        /// </summary>
        internal static string Zdx_x {
            get {
                return ResourceManager.GetString("Zdx_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 最后更新 的本地化字符串。
        /// </summary>
        internal static string Zhgx {
            get {
                return ResourceManager.GetString("Zhgx", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 最近2个财政年度经审计的财务报表 的本地化字符串。
        /// </summary>
        internal static string Zj2gczndjsjdcwbb {
            get {
                return ResourceManager.GetString("Zj2gczndjsjdcwbb", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 州省 的本地化字符串。
        /// </summary>
        internal static string Zs {
            get {
                return ResourceManager.GetString("Zs", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 至少选择一项 的本地化字符串。
        /// </summary>
        internal static string Zsxzyx {
            get {
                return ResourceManager.GetString("Zsxzyx", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 状态 的本地化字符串。
        /// </summary>
        internal static string Zt {
            get {
                return ResourceManager.GetString("Zt", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 主题 的本地化字符串。
        /// </summary>
        internal static string Zti {
            get {
                return ResourceManager.GetString("Zti", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 主题/方案 的本地化字符串。
        /// </summary>
        internal static string Zt_fa {
            get {
                return ResourceManager.GetString("Zt/fa", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 中文 的本地化字符串。
        /// </summary>
        internal static string Zw {
            get {
                return ResourceManager.GetString("Zw", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 中文名称 的本地化字符串。
        /// </summary>
        internal static string Zwmc {
            get {
                return ResourceManager.GetString("Zwmc", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 资讯网站 的本地化字符串。
        /// </summary>
        internal static string Zxwz {
            get {
                return ResourceManager.GetString("Zxwz", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 主用传真 的本地化字符串。
        /// </summary>
        internal static string Zycz {
            get {
                return ResourceManager.GetString("Zycz", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 主用电话 的本地化字符串。
        /// </summary>
        internal static string Zydh {
            get {
                return ResourceManager.GetString("Zydh", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 装运信息 的本地化字符串。
        /// </summary>
        internal static string Zyxx {
            get {
                return ResourceManager.GetString("Zyxx", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 主用银行 的本地化字符串。
        /// </summary>
        internal static string Zyyh {
            get {
                return ResourceManager.GetString("Zyyh", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 作者 的本地化字符串。
        /// </summary>
        internal static string Zzhe {
            get {
                return ResourceManager.GetString("Zzhe", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 制造生产实体 的本地化字符串。
        /// </summary>
        internal static string Zzscst {
            get {
                return ResourceManager.GetString("Zzscst", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 作者/提交日期 的本地化字符串。
        /// </summary>
        internal static string Zz_tjrq {
            get {
                return ResourceManager.GetString("Zz/tjrq", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 （中-） 的本地化字符串。
        /// </summary>
        internal static string Z_Z {
            get {
                return ResourceManager.GetString("Z_Z", resourceCulture);
            }
        }
    }
}
